---
title: "Distribution_Statistics"
author: "Tim Monko"
date: "`r Sys.Date()`"
output: html_document
---

```{r global_options, include = FALSE}
library(tidyverse) # Includes ggplot2, tidyr, dply*r, stringr, readr, tibble, purrr, forcats
library(svglite) # For exporting plots as .svg graphics to use as vector format
library(broom) # Tidy's up some statistical outputs
library(extrafont) # README: https://cran.r-project.org/web/packages/extrafont/README.html   // 
#font_import(path = 'C:/Users/TimMonko/AppData/Local/Microsoft/Windows/Fonts') # for custom installed .ttf fonts
library(unicycles)
library(ggh4x)
library(MANOVA.RM)
library(rstatix)
library(ggpubr)
extrafont::loadfonts(device = "win", quiet = TRUE) 
Sys.setenv(R_GSCMD="C:/Program Files/gs/gs9.52/bin/gswin64c.exe") # Set the location for Ghostscript for pdf embedding of fonts, use embed_fonts()

`%notin%` = Negate(`%in%`) # Used to define a group by what is NOT in the group
```


```{r data_management, echo = FALSE}
# echo = FALSE prevents printing of mundance code (can always set a function clause to echo = TRUE, if needed), by default echo = TRUE

wd.path <- getwd()
file.paths <- list.files(path = wd.path, pattern = '\\.csv$')

# Use all cols to identify certain columns as factors, without this it cannot generate the correct tibble, instead just forcing them into whatever it considers 'ideal'
all.cols <- cols(
  genotype = col_factor(),
  slice = col_factor(),
  pair = col_factor(),
  region = col_factor()
)

# A function for csv bind - brings in each file to create one master tibble 
csv_bind <- function(wd.path = getwd(), text.pattern, col.types){
  bound <- do.call(rbind,
                    lapply(list.files(path = wd.path, pattern = text.pattern),
                           function(x) read_csv(x, col_types = col.types)))
  return(bound)
}

# Use the function to call in files from getwd() [the default] based on the pattern within the file name
all.centers <- csv_bind(text.pattern = 'centers', col.types = all.cols) %>% mutate(genotype = factor(genotype, levels=c("WT", "CKO"))) 

# Likely the most useful datasets, the origin of the original analysis of investigating cell mean pooled across sections. *
summarize.cells<- csv_bind(text.pattern = 'cellmean', col.types = all.cols) %>% mutate(genotype = factor(genotype, levels=c("WT", "CKO"))) 

# This uses both relative bin and absolute bin distances as determined from the previously run R_Image_Analysis file, no helper .csv is yet available to show bin sizes and such 
# summarize.bins<- csv_bind(text.pattern = 'bins', col.types = all.cols)

```

```{r new_stats_short}
# Use below for lazy reorganization of factor levels  for slice in figures
# summarize.cells <- summarize.cells %>%
#   reorder_levels(slice, c(1,2,4,5,3,6,7,8,9,10,11,12,13,14,15)) 

summary.cells <- summarize.cells %>%
  group_by(genotype,slice, region) %>%
  get_summary_stats()


cells.out <- summarize.cells %>%
  group_by(slice,genotype,region) %>%
  identify_outliers(cells)

cells.norm <- summarize.cells %>%
  group_by(slice,genotype,region) %>% shapiro_test(cells)

rmpairs.1 <- c(1)
filt.region.1 <- c('S1')
rmpairs.2 <- c(3)
filt.region.2 <-c('V1')

rel.summarized <- summarize.cells %>%
  group_by(slice, pair, region) %>%
  summarize(CKO.rel = cells[genotype == "CKO"]/cells[genotype == "WT"]) %>%
  mutate(CKO.log = log(CKO.rel))

summary.rel <- rel.summarized %>%
  group_by(slice, region) %>%
  get_summary_stats(CKO.rel)


rm.rel.summarized <- rel.summarized %>%
  filter((pair %notin% c(rmpairs.1) & region %in% filt.region.1)|
         (pair %notin% c(rmpairs.2) & region %in% filt.region.2))

log.t <- rm.rel.summarized %>%
  group_by(slice, region) %>%
  t_test(CKO.log ~ 0, mu = 0) %>%
  add_significance()


# Change data to just cell counts in wide format, for ratiometric calculations
summarized.wide <- summarize.cells %>% 
  # filter(region == 'S1') %>% # should probably not filter by region here, because this will prevent good data management later - only remove when necessary 
  pivot_wider(id_cols = c(genotype, pair, region), names_from = slice, values_from = cells, names_prefix = 'cells_') # %>% replace(is.na(.),0) # NAs in the dataset become zero

# Divide columns to produce ratiometric data of X+ cell over Y+ cell or X+Y+ cell over Z cell, etc. 
summarized.manip <- summarized.wide %>%
  mutate(ROREdU_EdU = cells_6/cells_3) %>% # Brn2+EdU+/EdU+ cells (how many of the EdU cells are Brn2 labeled)
  mutate(Brn2EdU_EdU = cells_7/cells_3) %>%
  mutate(ROREdU_ROR = cells_6/cells_1) %>%
  mutate(Brn2EdU_Brn2 = cells_7/cells_2) %>%
  mutate(ROREdU_Brn2EdU = cells_6/cells_7) %>%
  mutate(EdUROR_EdUBrn2 = cells_8/cells_9) %>%
  mutate(doublenegs = cells_14/cells_15) %>%
  mutate(ROR_Brn2 = cells_1/cells_2) %>%
  mutate(Triple_EdU = cells_11/cells_3) %>%
  mutate(Triple_ROREdU = cells_10/cells_6) %>%
  mutate(Triple_Brn2EdU = cells_11/cells_7) %>%
  mutate(Triple_Brn2ROR = cells_11/cells_5)
  

# Grab column names to be used after the function call to a numeric column, could also be used as a vector of strings, but that seems like way too much work
summarized.col.names <- colnames(summarized.manip)
lastcells.col <- colnames(summarized.wide)
pairedcols <- setdiff(summarized.col.names, lastcells.col)

#this all uses rstatix which is better for pipes
summarized.long <- summarized.manip %>%
  pivot_longer(cols = all_of(pairedcols), names_to = "cells", values_to = "number") %>%
  mutate(cells = as_factor(cells))

summary.summarized <- summarized.long %>%
  group_by(genotype,cells,region) %>%
  get_summary_stats(number)

# Remove pairs using a numeric vector like c(). If logical then skipped to remove pairs 
rm.summarized.long <- summarized.long %>%
  filter((pair %notin% c(rmpairs.1) & region %in% filt.region.1)|
         (pair %notin% c(rmpairs.2) & region %in% filt.region.2))


paired.t <- rm.summarized.long %>%
  group_by(cells,region) %>%
  t_test(number ~ genotype, paired = TRUE) %>%
  add_significance()


log.t.bind <- log.t %>%
  rename(n1 = n, cells = slice)


#replications() seems useful to look at replicates of each terms in forumala 
summary.bind <-bind_rows(summary.cells, summary.rel, summary.summarized)
t.bind <- bind_rows(log.t.bind, paired.t)

cells.norm
cells.out
summary.bind
t.bind
write.table(t.bind, "clipboard-16384", sep = "\t", row.names = FALSE, quote = FALSE)

E18.summarized.long <- summarized.long %>% select(-starts_with("cells_"))

```

```{r plotting_means_new, echo = FALSE}
# Custom Gray Palette by Tim (no yellow) and slightly reorganized. Originally from: http://jfly.iam.u-tokyo.ac.jp/color/  and http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette
cbp.Rel <-c('#999999', '#E69F00', '#56B4E9', '#009E73', '#D55E00', '#0072B2', '#CC79A7')
cbp.Genotype <- c('#d95f02', '#7570b3')

plot_logtrans <- function(rmpairs, cells.to.plot, scale.labels, file.name, print.width = 6, print.height = 3) {
  rel.plot <- rel.summarized %>%
    filter(pair %notin% c(rmpairs)) %>%
    filter(slice %in% cells.to.plot)

  log.t.plot <- log.t %>% 
    filter(slice %in% cells.to.plot) %>%
    mutate(p.signif = recode(p.signif,"ns"= "")) %>%
    mutate(p = round(p, digits = 3)) %>%
    mutate(p = format(p, digits = 3)) %>%
    mutate(p = replace(p, p == 0, "<0.001")) 

plot.logtrans <- ggplot(rel.plot, aes(x=slice, y = CKO.rel, colour = slice, fill = slice, shape = slice)) +
    facet_nested_wrap(~region, strip.position = 'bottom', nrow = 1) +
    theme_classic(base_size = 7) +
    stat_summary(fun = "mean", geom = "col", width = 0.8, show.legend = FALSE) +
    geom_hline(aes(yintercept = 1), linetype = 'dashed') +
    geom_jitter(width = 0.1) +
    stat_pvalue_manual(log.t.plot, x = "slice", label ="{p}", y.position = 1.02, size = 2.5, family = "Helvetica", srt = 0) + # upon later investigation it apperas there is a hide.ns variable
    scale_fill_manual(values = alpha(cbp.Rel, 0.25), name = NULL, labels = scale.labels) +
    scale_colour_manual(values = cbp.Rel, name = NULL, labels = scale.labels) +
    scale_shape_manual(values = c(21,22,24,23,25,10,12), name = NULL, labels = scale.labels) + 
    labs(y = "Rel. Cell#, CKO/WT",
       x = NULL) + # can use element_blank for no label at all
    scale_x_discrete(breaks = NULL) +
    scale_y_continuous(trans = "log10", breaks = seq(0,10,0.2), minor_breaks = seq(0,10,0.1), guide = "axis_minor") + #guide + "axis_minor" from ggh4x package
    guides(color = guide_legend(override.aes = list(size = 2.5))) +
    coord_cartesian(clip = "off")


  plot.logtrans + theme_Tim() # theme(ggh4x.axis.ticks.length.minor = rel(1))
  ggsave(filename = paste0(file.name,'.png'), device = 'png', width = print.width*1.32, height = print.height*1.32, unit = 'cm', dpi = 1000)
  ggsave(filename = paste0(file.name,'.svg'), device = 'svg', width = print.width*1.32, height = print.height*1.32, unit = 'cm')
  print(plot.logtrans + theme_Tim())
}

plot_logtrans(rmpairs = c(0), cells.to.plot = c(1,2,5), scale.labels = c('ROR', 'BRN2', 'BRN2+ROR+'), file.name = "logtrans-IHC-col", print.width = 5, print.height = 3)

plot_logtrans(rmpairs = c(0), cells.to.plot = c(3,6,7), scale.labels = c('EdU+', 'ROR+EdU+', 'BRN2+EdU+'), file.name = "logtrans-EDU-col", print.width = 5, print.height = 3)


plot_logtrans(rmpairs = c(0), cells.to.plot = c(1,2,5,3,6,7), scale.labels = c('ROR+', 'BRN2+', 'ROR+BRN2+', 'EdU+', 'ROR+EdU+', 'BRN2+EdU+'), file.name = "logtrans-allcells-col", print.width = 6.5, print.height = 3)
```

```{r plotting_ratiometric_new, echo = FALSE}
# Custom Gray Palette by Tim (no yellow) and slightly reorganized. Originally from: http://jfly.iam.u-tokyo.ac.jp/color/  and http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/#a-colorblind-friendly-palette
cbp.Rel <-c('#999999', '#E69F00', '#56B4E9', '#009E73', '#D55E00', '#0072B2', '#CC79A7')
cb.Genotype <- c('#d95f02', '#7570b3')

plot_ratio <- function(rmpairs, cells.to.plot, file.name, print.width = 4, print.height = 3) {
  ratio.plot <- summarized.long %>%
    filter((pair %notin% c(rmpairs.1) & region %in% filt.region.1)|
           (pair %notin% c(rmpairs.2) & region %in% filt.region.2)) %>%
    filter(cells %in% cells.to.plot)

  paired.t.plot <-  summarized.long %>%
    filter((pair %notin% c(rmpairs.1) & region %in% filt.region.1)|
           (pair %notin% c(rmpairs.2) & region %in% filt.region.2)) %>%
    filter(cells %in% c(cells.to.plot)) %>%
    group_by(cells,region) %>%
    t_test(number ~ genotype, paired = TRUE) %>%
    add_significance() %>%
    add_xy_position() %>%
    mutate(p.signif = recode(p.signif,"ns"= "")) %>%
    mutate(p = round(p, digits = 3)) %>%
    mutate(p = format(p, digits = 3)) %>%
    mutate(p = replace(p, p == 0, "<0.001")) 

  plot.ratio <- ggplot(ratio.plot, aes(x = genotype, y = number, colour = genotype)) +
    facet_nested_wrap(~region * cells, scales = "fixed", strip.position = 'bottom', nrow = 1) +
    theme_classic(base_size = 7) +
    geom_jitter(size = 1, shape = 21, width = 0.03, aes(fill = genotype)) +
    stat_summary(fun = "mean", geom = "point", size = 5, aes(shape = genotype, color = genotype)) +
    stat_pvalue_manual(paired.t.plot, label ="{p}", size = 2.5, family = "Helvetica", bracket.nudge.y = 0.005) +
    labs(y = 'Ratio',
       x = element_blank()) +
    scale_x_discrete(breaks = NULL) +
    scale_colour_manual(values = cbp.Genotype) +
    scale_fill_manual(values = alpha(cbp.Genotype, 0.25)) +
    scale_shape_manual(values = c(7,10)) +
    guides(fill = guide_legend(title = "Genotype"),
           color = guide_legend(title = "Genotype",   
                              label.position = 'left',
                              label.hjust = 1),
           shape = guide_legend(title = "Genotype",
                              override.aes = list(size = 2.5),   
                              label.position = 'left',
                              label.hjust = 1))+
    coord_cartesian(clip = "off") #size = 3 reduces the key icon for the colour header to a smaller size 
  plot.ratio + theme_Tim()
  ggsave(filename = paste0(file.name,'.png'), device = 'png', width = print.width*1.32, height = print.height*1.32, unit = 'cm', dpi = 1000)
  ggsave(filename = paste0(file.name,'.svg'), device = 'svg', width = print.width*1.32, height = print.height*1.32, unit = 'cm')
  print(plot.ratio + theme_Tim())
}


plot_ratio(rmpairs = c(0), cells.to.plot = c("ROREdU_Brn2EdU"), file.name = "ROREdU_Brn2EdU", print.width = 3.5, print.height = 3.5)
plot_ratio(rmpairs = c(0), cells.to.plot = c("ROREdU_ROR", "Brn2EdU_Brn2"), file.name = "Doubles_Singles", print.width = 5.5, print.height = 3.5)
plot_ratio(rmpairs = c(0), cells.to.plot = c("ROREdU_EdU", "Brn2EdU_EdU"), file.name = "Doubles_EdU", print.width = 5.5, print.height = 3.5)

plot_ratio(rmpairs = c(0), cells.to.plot = c("Triple_ROREdU"), file.name = "Ratio-Triple_ROREdU", print.width = 3.5, print.height = 3.5)

```


``` {r plotting_distribution_WTCKO_by_pairs, echo = FALSE}

## Trying to plot the distribution of all cells along one axis 
# Y-axis- top = 0, distance from pial surface
# X-axis density 

cbp.Dist <- c('#E69F00', '#56B4E9', '#009E73',  '#CC79A7') #'#D55E00', '#0072B2',

cells.to.dist <- c(1,2,3)
rmpairs.dist <- c(0)

dist.centers <- all.centers %>%
  filter(between(mx.abs.right, 0, 600)) %>%
  filter(slice %in% cells.to.dist)

center.means <- dist.centers %>%
  group_by(genotype, region, slice) %>%
  filter(pair%notin% c(rmpairs)) %>%
  summarize(group.medx = median(mx.abs.right), group.mx = mean(mx.abs.right))

dist.plot <- dist.centers %>%
  filter(pair %notin% c(rmpairs))


plot.dist <- ggplot(dist.plot, aes(mx.abs.right, color = slice,fill = slice)) +
  facet_nested_wrap(~ region*genotype, nrow = 1, scales = "free_x") +
  theme_classic(base_size = 7) +
  geom_density(kernel = "gaussian", bw = "nrd0", adjust = 0.5, alpha = 0.3, aes(y = ..count..)) +
  #stat_summary(fun = "median", geom = "vline", aes(x=0.1, y = mx.abs.right, xintercept = stat(y), group = slice)) +
  geom_vline(data = center.means, aes(xintercept = group.medx, color = slice), linetype = "dashed") +
  scale_fill_manual(values = cbp.Dist, name = NULL, labels = c('ROR', 'Brn2', 'EdU', 'ROR+Brn2+')) +
  scale_color_manual(values = cbp.Dist, guide = FALSE) +
  coord_flip() + 
  scale_x_reverse(limits = c(600,0),n.break=6) +
  scale_y_continuous(expand = c(0.001,0), breaks = NULL, labels = NULL) +
  labs(y = NULL,
       x = "Distance from pia, μm") +
  guides(fill = guide_legend(label.position = 'left',
                             label.hjust = 1))

plot.dist
```

```{r distribution_save, echo=FALSE}
plot.dist + theme_Tim()  # theme_Tim was adapted from the Ib packaged and installed now using Tim Monko's custom package 'unicycles'


ggsave(filename = paste0('New_DistributionPairs2count-new.png'), device = 'png', width = 7*1.32, height = 4*1.32, unit = 'cm', dpi = 1000)
ggsave(filename = paste0('New_DistributionPairs2count-new.svg'), device = 'svg', width = 4*1.32, height = 4*1.32, unit = 'cm')

```

```{r distribution_stats_plots, echo=FALSE}

pull_dist <- function(geno, slice.pull, variable){
  all.centers %>%
  filter(genotype == geno) %>%
  filter(slice == slice.pull) %>%
  filter(between(mx.abs.right, 0, 600)) %>%
  pull({{variable}})
}

dist.x <- pull_dist("CKO", 6, mx.abs.right)
dist.y <- pull_dist("WT", 6, mx.abs.right)

ks.test(dist.x, dist.y)

##grouping by cells keeps each section in tact, without having to group by file, this gives the percentage per section, I think (see other file)
count.random <- all.centers %>%
  mutate(rand = runif(n(), min=50, max=275)) %>%
  mutate(binned.mx = cut(rand, breaks = seq(50,275,25), right = TRUE, ordered_result = TRUE)) %>%
  filter(!is.na(binned.mx)) %>%
  group_by(genotype, slice, pair, region, binned.mx,file,cells) %>%
  summarize(rand.count.bin = n()/n_distinct(file)) %>% 
  replace_na(list(rand.count.bin = 0)) %>%
  mutate(count.perc = rand.count.bin/cells)

count <- all.centers %>%
  mutate(binned.mx = cut(mx.abs.right, breaks = seq(50,275,25), right = TRUE, ordered_result = TRUE)) %>%
  filter(!is.na(binned.mx)) %>%
  group_by(genotype, slice, pair, region, binned.mx,file,cells) %>%
  summarize(count.bin = n()/n_distinct(file)) %>% 
  replace_na(list(count.bin = 0)) %>%
  mutate(count.perc = count.bin/cells) 

count2 <- count %>%
  group_by()


count.random2 <- count.random %>% ungroup() %>% select(genotype:file)
count2 <- count %>% ungroup()
count.join2 <- left_join(count.random2, count2) %>% 
    replace_na(list(count.rel = 0)) 


#the juicy bits to get ROREdU / TOTAL EdU 
count.x <- count.join2 %>% 
  filter(slice == 1) %>%
  ungroup() %>%
  select(genotype:count.perc, -slice) 
count.y <- count.join2 %>%
  filter(slice == 6) %>%
  ungroup() %>%
  select(genotype:count.perc, -slice) 

stat.count.join <- left_join(count.x, count.y, by = c("genotype", "pair", "region", "binned.mx", "file")) %>%
  replace_na(list(count.bin.y = 0)) %>%
  replace_na(list(count.bin.x = 0)) %>%
  mutate(count.y_count.x = count.bin.y/count.bin.x) %>%
  mutate(diff.x_y = count.bin.x - count.bin.y) %>%
  mutate(rel.diff.xy = count.bin.y/(count.bin.x-count.bin.y)) %>%
  mutate(perc.diff = count.perc.y-count.perc.x) %>%
  mutate(perc.diff.x_y = count.perc.y/count.perc.x)



rmpairs.stat <- c(0)

stat.count.join.mean <- stat.count.join %>%
  group_by(genotype,pair,region,binned.mx) %>%
  summarize(rel.mean = mean(count.y_count.x), diff.mean = mean(diff.x_y), rel.diff.mean = mean(rel.diff.xy), perc.diff.mean = mean(perc.diff), perc.diffxy.mean = mean(perc.diff.x_y)) %>%
  replace_na(list(rel.mean = 0)) %>%
    replace_na(list(rel.diff.mean = 0)) %>%
  mutate(rel.diff.mean = replace(rel.diff.mean, rel.diff.mean == Inf, 0))%>%
  filter(pair %notin% rmpairs.stat) %>%
  ungroup() %>%
  mutate(id = paste0(genotype,pair)) %>%
  mutate(binned.mx = as_factor(as.character(binned.mx)))


# Linear models can be used here because the bins are treated distinctly

perc.lm <- lm(perc.diff.mean ~ genotype * binned.mx, data = stat.count.join.mean)
summary(perc.lm)
summary.aov(perc.lm)

slice.to.dist <- c(1,6)
plot.count <- count.join2 %>%
  filter(slice %in% slice.to.dist) %>%
  group_by(genotype,pair,slice, region,binned.mx) %>%
  summarize(bin.mean = mean(count.bin), perc.mean = mean(count.perc)) %>%
  replace_na(list(rel.mean = 0)) %>%
  replace_na(list(perc.mean = 0)) %>%
  mutate(id = paste0(genotype,slice))


bin.facet.ggplot <- ggplot(data = plot.count, aes(x=binned.mx, y = perc.mean, color = slice, fill = slice, shape = slice)) +
  facet_nested_wrap(~ region * genotype, nrow = 1, scales = "fixed") +
  theme_classic(base_size = 7) +
  #geom_jitter(size = 0.7, width = 0.1) +
  stat_summary(fun = "mean", geom = "line", size = 0.8, alpha = 0.8, aes(group = id)) +
  stat_summary(fun = "mean", geom = "point", size = 2, alpha = 0.5, aes(group = id)) +
  stat_summary(fun.data = "mean_se", geom = "errorbar", size = 0.5, alpha = 0.8, aes(group = id), width = 0.5) +
  #stat_boxplot(linetype = 1,outlier.size = 0.5, size = 0.3) +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_discrete(limits=rev) +
  #scale_fill_manual(values = cbp.Dist, name = NULL, labels = c('ROR', 'Brn2', 'EdU', 'ROR+Brn2+')) +
  scale_colour_manual(values = cbp.Dist, name = NULL, labels = c('ROR', 'ROR+EdU+')) +
  scale_fill_manual(values = alpha(cbp.Dist, 0.4), name = NULL, labels = c('ROR', 'ROR+EdU+')) +
  scale_shape_manual(values = c(21,22,24), name = NULL, labels = c('ROR', 'ROR+EdU+')) +
  scale_linetype_manual(values = c(1,2,4), name = NULL, labels = c('ROR', 'ROR+EdU+')) +
  coord_flip() + 
  labs(x = "Distance from pia, μm",
       y = "Cells in bin/All cells") +
  guides(shape = guide_legend(),
         linetype = guide_legend(),
         color = guide_legend(label.position = 'left',
                             label.hjust = 1))



bin.facet.ggplot + theme_Tim()
```


```{r distribution_save, echo=FALSE}
bin.facet.ggplot +theme_Tim() # theme_Tim was adapted from the Ib packaged and installed now using Tim Monko's custom package 'unicycles'


ggsave(filename = paste0('DistBoxesmeanSE2-new2.png'), device = 'png', width = 11*1.32, height = 5*1.32, unit = 'cm', dpi = 1000)
ggsave(filename = paste0('DistBoxesmeanSE2-new2.svg'), device = 'svg', width = 11*1.32, height = 5*1.32, unit = 'cm')

```