---
title: "R_Image_Analysis"
author: "Tim Monko"
date: "`r Sys.Date()`"
output: html_document
---

```{r global_options, include = FALSE}
library(tidyverse) # Includes ggplot2, tidyr, dplyr, stringr, readr, tibble, purrr, forcats
library(svglite) # For exporting plots as .svg graphics to use as vector format
library(broom) # Tidy's up some statistical outputs
library(magick) # A more general image altering package
library(imager) # For loading of stacks, I think to be used with magick
```

```{r cache_settings, echo = FALSE}

dir.name <- 'Pair1-12_RORBrn2EdU-P8-E14EdU'
dir.create(dir.name)

knitr::opts_chunk$set(cache = TRUE, cache.path = paste0(dir.name, '-cache/')) # fig.path = 'Figs/' ## Will save figs into a separate file 
```

```{r data_management, echo = FALSE}
# echo = FALSE prevents printing of mundance code (can always set a function clause to echo = TRUE, if needed), by default echo = TRUE

rescale <- 0.63492 # For 10X its 0.63492 (1/1.575)
region <- 'S1'

wd.path <- getwd() # The .Rmd file needs to be saved into the parent folder of the images, else getwd() does not work within RMarkdown 
file.paths <- list.files(path = wd.path, pattern = '\\.tif$') # $ at end searches for all files ending in .tif
file.number <- length(file.paths)

dist <- image_read(file.paths[1])
names <- as.character(1:length(dist))

print(region)
```


```{r new_no_interact, echo = FALSE}
rm(all.centers)
for (im in 1:file.number) {

  dist <- image_read(file.paths[im])
  dist.tif <- magick2cimg(dist)
  
  # dim(dist.tif) [width, height, depth, channels]
  dist.dims <- dim(dist.tif)
  dist.width <- dist.dims[1] 
  dist.height <- dist.dims[2]
  dist.depth <- dist.dims[3]

  for (slice in 1:dist.depth) {
    px.dist <- dist.tif[,,slice,] > 0.5 # This code selects are pixels above an intensity of 50%, this only matters if the image was straightened in FIJI
    px.cimg <- as.cimg(px.dist) 
    pixset.dist <- as.pixset(px.cimg)
    pix.labels <- label(pixset.dist) # Create a unique identifier for contiguous pixels 
    df.labels <- as.data.frame(pix.labels) %>% subset(value > 0) 
    number.of.cells <- unique(df.labels$value) %>% max() #Count the number of unique identifiers to determine cell number
    df.centers <- as_tibble(df.labels) %>%
      group_by(value) %>%
      summarise(mx = mean(x), my = mean(y)) %>% # As labels are stored as a series of pixel coordinates for each pixel, this determines the center of mass of a binary cell
      mutate(cells = number.of.cells) %>%
      mutate(file = file.paths[im]) %>%
      mutate(age = 'P8') %>%
      mutate(edu = 'E16') %>%
      mutate(genotype = str_extract(file.paths[im], 'WT|CKO')) %>% 
      mutate(slice = slice) %>%
      mutate(image = im) %>%
      mutate(pair = str_extract(file.paths[im], '(?<=Pr)[:digit:]{1,2}')) %>%
      mutate(region = str_extract(file.paths[im], 'S1|V1')) %>%
      mutate(mx.rel = mx/dist.width) %>% # The relative value of the cells position from the left to the right of the x axis
      mutate(mx.abs.right = (dist.width-mx)*rescale) %>% # The absolute value on the x-axis from the right side, likely the pial surface
      mutate(mx.abs.left  = mx*rescale) %>% # The absolute value on the x-axis in um for the cells position, likely the ventricle
      mutate(my.rel = my/dist.height) %>%
      mutate(dist.width = dist.width) %>%
      mutate(dist.height = dist.height) 
      
    test <- exists('all.centers')
    
    if (test == FALSE) {
      all.centers <- df.centers
    } else {
      all.centers <- bind_rows(all.centers, df.centers)  
    }
  }
}
```

```{r plotting_stats, echo = FALSE}
# For plotting only, well not really, this is used for the subsequent images
plot.df <- all.centers %>%
  mutate(binned.mx.rel = cut(mx.rel, breaks = seq(0,1,0.1), labels = c(0:9))) %>% # Demarcate 10% bins
  mutate(binned.mx.abs = cut(mx.abs.right, breaks = seq(0, 1400, 100), labels = c(0:13))) # Label distance bins, use the Seq to set bin size 

pair <- unique(all.centers$pair)

# For excel sheets 
binned.rel <- plot.df %>%
  group_by(genotype, slice, pair, region, binned.mx.rel) %>%
  summarize(count.rel = n()/n_distinct(file))

binned.abs <- plot.df %>%
  group_by(genotype, slice, pair, region, binned.mx.abs) %>%
  summarize(count.abs = n()/n_distinct(file)) 

# Pivoted bins are for saving to a summarized sheet
pivot.binned.rel <- binned.rel %>% pivot_wider(names_from = binned.mx.rel, names_prefix = 'rel_', values_from = count.rel, values_fill = list(count.rel = 0)) %>%   
  select(order(colnames(.)))

pivot.binned.abs <- binned.abs %>% pivot_wider(names_from = binned.mx.abs, names_prefix = 'abs_', values_from = count.abs, values_fill = list(count.rel = 0)) %>%   
  select(order(colnames(.)))

# pivot.binned.rel[is.na(pivot.binned.rel)] <- 0
# pivot.binned.abs[is.na(pivot.binned.abs)] <- 0

  
summarized <- all.centers %>%
  #mutate(binned.mx.rel = cut(mx.rel, breaks = seq(0,1,0.1), labels = c(0:9))) %>% 
  #mutate(binned.mx.abs = cut(mx.abs.right, breaks = seq(0, 1400, 100), labels = c(0:13))) %>%
  group_by(genotype, slice, pair, region) %>%
  summarize_if(is.numeric, mean) %>%
  select(genotype, slice, pair, region, mx, my, mx.rel, mx.abs.right, mx.abs.left, my.rel, dist.width, dist.height)

summarized.bound <- bind_cols(summarized, pivot.binned.rel, pivot.binned.abs)

cell.section.summarized <- all.centers %>%
  select(cells, file, genotype, slice, image, pair, region)%>%
  distinct() 

cell.summarized.mean <- cell.section.summarized %>%
  group_by(genotype, slice, pair, region) %>%
  summarize(cells = mean(cells))

cell.section.pivot <- cell.section.summarized %>% 
  pivot_wider(id_cols = c(file, genotype, image, pair, region), names_from = slice, values_from = cells, names_prefix = 'slice_')

# df.WT <- filter(plot.df, genotype == 'WT' && slice == 4)
# df.cKO <- filter(plot.df, genotype == 'CKO' && slice == 4)
# kst <- ks.test(df.WT$mx.abs.right, df.cKO$mx.abs.right)
# t <- t.test(df.WT$mx.abs.right, df.cKO$mx.abs.right)
# 
# print(tidy(t))
# print(tidy(kst))

print(summarized.bound)

density.plot <- ggplot(data = plot.df, (aes(x = mx.abs.right, fill = genotype, family = 'sans'))) +
  facet_wrap(~ slice, strip.position = 'top', scales = 'free_y') +
  theme_classic(base_size = 13) +
  geom_density(kernel = 'gaussian', adjust = 0.3, alpha = 0.5) + 
  geom_vline(data = summarized, aes(xintercept = mx.abs.left, color = genotype), linetype = 'dashed')
density.plot

#ggsave(path = paste0(wd.path, '/', dir.name, '/'), filename = 'denisty_plot.png', device = 'png', width = 15*1.32, height = 8*1.32, unit = 'cm', dpi = 1000)
#ggsave(path = paste0(wd.path, '/', dir.name, '/'), filename = 'density_plot.svg', device = 'svg', width = 15*1.32, height = 8*1.32, unit = 'cm')

binned.rel.plot <- ggplot(data = binned.rel, (aes(x = binned.mx.rel, y = count.rel, fill = genotype))) +
  facet_wrap(~slice, strip.position = 'top', scales = 'free_y') +
  theme_classic(base_size = 13) +
  geom_col(position = position_dodge(preserve = 'single'))
binned.rel.plot

#ggsave(path = paste0(wd.path, '/', dir.name, '/'), filename = 'binned_rel_plot.png', device = 'png', width = 15*1.32, height = 8.1*1.32, unit = 'cm', dpi = 1000)
#ggsave(path = paste0(wd.path, '/', dir.name, '/'), filename = 'binned_rel_plot.svg', device = 'svg', width = 15*1.32, height = 8.1*1.32, unit = 'cm')

binned.abs.plot <- ggplot(data = binned.abs, (aes(x = binned.mx.abs, y = count.abs, fill = genotype))) +
  facet_wrap(~slice, strip.position = 'top', scales = 'free_y') +
  theme_classic(base_size = 13) +
  geom_col(position = position_dodge(preserve = 'single')) 
binned.abs.plot

#ggsave(path = paste0(wd.path, '/', dir.name, '/'), filename = 'binned_abs_plot.png', device = 'png', width = 15*1.32, height = 8.1*1.32, unit = 'cm', dpi = 1000)
#ggsave(path = paste0(wd.path, '/', dir.name, '/'), filename = 'binned_abs_plot.svg', device = 'svg', width = 15*1.32, height = 8.1*1.32, unit = 'cm')

```

```{r saving_things, echo = FALSE}

write_csv(all.centers,      path = paste0(wd.path, '/', dir.name, '/', dir.name, '_all_centers.csv'))
#write_csv(binned.abs,     path = paste0(wd.path, '/', dir.name, '/', dir.name, '_binned_abs.csv'))
#write_csv(binned.rel,     path = paste0(wd.path, '/', dir.name, '/', dir.name, '_binned_rel.csv'))
write_csv(summarized.bound, path = paste0(wd.path, '/', dir.name, '/', dir.name, '_summarized_bins.csv'))
write_csv(cell.section.pivot, path = paste0(wd.path, '/', dir.name, '/', dir.name, '_section_counts.csv'))
write_csv(cell.summarized.mean, path = paste0(wd.path, '/', dir.name, '/', dir.name, '_summarized_cellmean.csv'))
```

